### ISSUE TITLE
docker build -t epc-web:mybuild ./ not work

### ISSUE THREAD

**Issue by stolaf** [scusi/epc-web#1]
Sending build context to Docker daemon  466.4kB
Step 1/20 : FROM golang:1.18.0-stretch AS builder
 ---> 3c14e0626782
Step 2/20 : ENV GO111MODULE=on     CGO_ENABLED=1
 ---> Using cache
 ---> 30c208977547
Step 3/20 : WORKDIR /build
 ---> Using cache
 ---> e78f0cace505
Step 4/20 : COPY go.mod .
 ---> Using cache
 ---> 40d993a2ffbb
Step 5/20 : RUN go mod download
 ---> Using cache
 ---> 524bdf2e7b76
Step 6/20 : COPY . .
 ---> Using cache
 ---> b8eedcf05486
Step 7/20 : RUN go build ./cmd/epc-web
 ---> Running in 96207baee99e
stat /build/cmd/epc-web: directory not found

**Comment by scusi** [comment]
fixed with commit 2b328a7 and 1f99d22
